import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "/components/Sidebar";
import GlobalHeader from "/components/GlobalHeader";
import GlobalFooter from "/components/GlobalFooter";
import { AuthProvider } from "/components/auth-context";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-w-screen min-h-screen`}>
				<AuthProvider>

					<div className={` w-screen`}>
						<GlobalHeader />
						{/* <Sidebar /> */}
						<main className="flex-1 bg-gray-100">
							<div className="">{children}</div>
						</main>
						<GlobalFooter />
					</div>

				</AuthProvider>





			</body>
		</html>
	);
}
